server:
  port: 5000

spring:
  datasource:

    url: jdbc:mysql://localhost:3306/news
    username: root
    password: hbstudent


  jpa:
    generate-ddl: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yaml

